spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fantomas?useSSL=false
    username: root
    password: Nachtgestalt06
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true